/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SecretRouteImport } from './routes/secret'
import { Route as NousRouteImport } from './routes/nous'
import { Route as LettreRouteImport } from './routes/lettre'
import { Route as GalerieRouteImport } from './routes/galerie'
import { Route as DecouverteRouteImport } from './routes/decouverte'
import { Route as IndexRouteImport } from './routes/index'

const SecretRoute = SecretRouteImport.update({
  id: '/secret',
  path: '/secret',
  getParentRoute: () => rootRouteImport,
} as any)
const NousRoute = NousRouteImport.update({
  id: '/nous',
  path: '/nous',
  getParentRoute: () => rootRouteImport,
} as any)
const LettreRoute = LettreRouteImport.update({
  id: '/lettre',
  path: '/lettre',
  getParentRoute: () => rootRouteImport,
} as any)
const GalerieRoute = GalerieRouteImport.update({
  id: '/galerie',
  path: '/galerie',
  getParentRoute: () => rootRouteImport,
} as any)
const DecouverteRoute = DecouverteRouteImport.update({
  id: '/decouverte',
  path: '/decouverte',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/decouverte': typeof DecouverteRoute
  '/galerie': typeof GalerieRoute
  '/lettre': typeof LettreRoute
  '/nous': typeof NousRoute
  '/secret': typeof SecretRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/decouverte': typeof DecouverteRoute
  '/galerie': typeof GalerieRoute
  '/lettre': typeof LettreRoute
  '/nous': typeof NousRoute
  '/secret': typeof SecretRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/decouverte': typeof DecouverteRoute
  '/galerie': typeof GalerieRoute
  '/lettre': typeof LettreRoute
  '/nous': typeof NousRoute
  '/secret': typeof SecretRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/decouverte' | '/galerie' | '/lettre' | '/nous' | '/secret'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/decouverte' | '/galerie' | '/lettre' | '/nous' | '/secret'
  id:
    | '__root__'
    | '/'
    | '/decouverte'
    | '/galerie'
    | '/lettre'
    | '/nous'
    | '/secret'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DecouverteRoute: typeof DecouverteRoute
  GalerieRoute: typeof GalerieRoute
  LettreRoute: typeof LettreRoute
  NousRoute: typeof NousRoute
  SecretRoute: typeof SecretRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/secret': {
      id: '/secret'
      path: '/secret'
      fullPath: '/secret'
      preLoaderRoute: typeof SecretRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nous': {
      id: '/nous'
      path: '/nous'
      fullPath: '/nous'
      preLoaderRoute: typeof NousRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lettre': {
      id: '/lettre'
      path: '/lettre'
      fullPath: '/lettre'
      preLoaderRoute: typeof LettreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galerie': {
      id: '/galerie'
      path: '/galerie'
      fullPath: '/galerie'
      preLoaderRoute: typeof GalerieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decouverte': {
      id: '/decouverte'
      path: '/decouverte'
      fullPath: '/decouverte'
      preLoaderRoute: typeof DecouverteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DecouverteRoute: DecouverteRoute,
  GalerieRoute: GalerieRoute,
  LettreRoute: LettreRoute,
  NousRoute: NousRoute,
  SecretRoute: SecretRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
